name: es_utils
description: A Flutter package for few UI components like confirmDialog, inputDialog, Buttons etc
version: 1.0.16
homepage: https://erratums.com
repository: https://github.com/ajumalp/flutter_es_utils

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  url_launcher: ^6.1.5
  http: ^0.13.5
  intl: ^0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:
  uses-material-design: true
