name: Flutter

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches: [main]

# on: push    # Default will running for every branch.

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # 'dev', 'alpha', 'beta', default to: 'stable'
          flutter-version: "2.8.0" # you can also specify exact version of flutter

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      # - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze

      # Run
      - run: flutter doctor -v

      # Run widget tests for our flutter project.
      - run: flutter test
